// Generated by scripts/generate-model-registry.mjs from data/models/. Do not edit by hand.
// Sources: aliases.json, anthropic.json, cohere.json, deepseek.json, google.json, groq.json, llamacpp.json, lmstudio.json, mistral.json, openai.json, provenance.json
// Run `npm run registry:generate` after changing the data, and `npm run registry:check` to verify.

import type { AliasMetadata, ModelCapabilities } from '../types/providers.js';

/** Provenance of the generated data, mirroring data/models/provenance.json. */
export const GENERATED_REGISTRY_PROVENANCE = {
  "verifiedAt": "2026-08-25",
  "source": "provider documentation"
} as const;

/** Every model defined in the versioned provider data, sorted by name. */
export const GENERATED_MODELS: Record<string, ModelCapabilities> = {
  "claude-3-5-haiku-20241022": {
    "provider": "anthropic",
    "family": "claude-haiku-3.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0008,
    "costPer1kOutput": 0.004,
    "costPer1kCachedInput": 0.00008000000000000002,
    "costPer1kCacheWrite": 0.001,
    "qualityScore": 78,
    "speedScore": 96,
    "release": "2024-10-22",
    "knowledgeCutoff": "2024-07",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-3-5-sonnet-20240620": {
    "provider": "anthropic",
    "family": "claude-3.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 84,
    "speedScore": 82,
    "release": "2024-06-20",
    "knowledgeCutoff": "2024-04",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-3-5-sonnet-20241022": {
    "provider": "anthropic",
    "family": "claude-3.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 86,
    "speedScore": 84,
    "release": "2024-10-22",
    "knowledgeCutoff": "2024-04",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-3-7-sonnet-20250219": {
    "provider": "anthropic",
    "family": "claude-3.7",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 89,
    "speedScore": 84,
    "release": "2025-02-19",
    "knowledgeCutoff": "2024-10",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-3-haiku-20240307": {
    "provider": "anthropic",
    "family": "claude-haiku-3",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0.00025,
    "costPer1kOutput": 0.00125,
    "costPer1kCachedInput": 0.000025,
    "costPer1kCacheWrite": 0.0003125,
    "qualityScore": 68,
    "speedScore": 94,
    "release": "2024-03-07",
    "knowledgeCutoff": "2023-08",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-fable-5-0": {
    "provider": "anthropic",
    "family": "claude-fable-5.0",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 96,
    "speedScore": 92,
    "release": "2026",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-haiku-4-5-20251001": {
    "provider": "anthropic",
    "family": "claude-haiku-4.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.001,
    "costPer1kOutput": 0.005,
    "costPer1kCachedInput": 0.0001,
    "costPer1kCacheWrite": 0.00125,
    "qualityScore": 86,
    "speedScore": 98,
    "release": "2025-10-01",
    "knowledgeCutoff": "2025-02",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-haiku-5-0": {
    "provider": "anthropic",
    "family": "claude-haiku-5.0",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.001,
    "costPer1kOutput": 0.005,
    "costPer1kCachedInput": 0.0001,
    "costPer1kCacheWrite": 0.00125,
    "qualityScore": 88,
    "speedScore": 98,
    "release": "2026",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-1-20250805": {
    "provider": "anthropic",
    "family": "claude-opus-4.1",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 24000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 32000,
    "costPer1kInput": 0.015,
    "costPer1kOutput": 0.075,
    "costPer1kCachedInput": 0.0015,
    "costPer1kCacheWrite": 0.01875,
    "qualityScore": 97,
    "speedScore": 70,
    "release": "2025-08-05",
    "knowledgeCutoff": "2025-03",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-20250514": {
    "provider": "anthropic",
    "family": "claude-opus-4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 24000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 32000,
    "costPer1kInput": 0.015,
    "costPer1kOutput": 0.075,
    "costPer1kCachedInput": 0.0015,
    "costPer1kCacheWrite": 0.01875,
    "qualityScore": 95,
    "speedScore": 70,
    "release": "2025-05-14",
    "knowledgeCutoff": "2025-03",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-5-20251101": {
    "provider": "anthropic",
    "family": "claude-opus-4.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 96000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 97,
    "speedScore": 72,
    "release": "2025-11-01",
    "knowledgeCutoff": "2025-08",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "notes": "Anthropic Claude Code Bedrock docs reference this Opus 4.5 snapshot; verify direct Claude API availability before production use."
  },
  "claude-opus-4-6": {
    "provider": "anthropic",
    "family": "claude-opus-4.6",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 96000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 98,
    "speedScore": 72,
    "release": "2026",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "notes": "Anthropic docs reference claude-opus-4-6 for Claude Code and batch beta usage; verify account and platform availability."
  },
  "claude-opus-4-7": {
    "provider": "anthropic",
    "family": "claude-opus-4.7",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 96000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 99,
    "speedScore": 72,
    "release": "2026",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-8": {
    "provider": "anthropic",
    "family": "claude-opus-4.8",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 96000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 99,
    "speedScore": 74,
    "release": "2026",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-sonnet-4-20250514": {
    "provider": "anthropic",
    "family": "claude-sonnet-4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 92,
    "speedScore": 86,
    "release": "2025-05-14",
    "knowledgeCutoff": "2025-03",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-sonnet-4-6": {
    "provider": "anthropic",
    "family": "claude-sonnet-4.6",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 96,
    "speedScore": 88,
    "release": "2026",
    "knowledgeCutoff": "2025-08",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-sonnet-5-0": {
    "provider": "anthropic",
    "family": "claude-sonnet-5.0",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 96,
    "speedScore": 88,
    "release": "2026",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "cohere/c4ai-aya-expanse-32b": {
    "provider": "cohere",
    "family": "aya-expanse",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 76,
    "speedScore": 84,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/c4ai-aya-vision-32b": {
    "provider": "cohere",
    "family": "aya-vision",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 16000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 78,
    "speedScore": 78,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-03-2025": {
    "provider": "cohere",
    "family": "command-a",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 86,
    "speedScore": 80,
    "release": "2025-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-reasoning-08-2025": {
    "provider": "cohere",
    "family": "command-a-reasoning",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 32000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 88,
    "speedScore": 68,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-translate-08-2025": {
    "provider": "cohere",
    "family": "command-a-translate",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 82,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-vision-07-2025": {
    "provider": "cohere",
    "family": "command-a-vision",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 78,
    "release": "2025-07",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r": {
    "provider": "cohere",
    "family": "command-r",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 78,
    "speedScore": 92,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r-plus": {
    "provider": "cohere",
    "family": "command-r-plus",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 82,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r7b-12-2024": {
    "provider": "cohere",
    "family": "command-r7b",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 74,
    "speedScore": 94,
    "release": "2024-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/tiny-aya-global": {
    "provider": "cohere",
    "family": "tiny-aya",
    "modalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 62,
    "speedScore": 98,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "deepseek/deepseek-chat": {
    "provider": "deepseek",
    "family": "deepseek-chat",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 64000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 82,
    "speedScore": 84,
    "release": "stable",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing and limits vary by DeepSeek account; override costs in models.registry for exact estimates."
  },
  "deepseek/deepseek-r1": {
    "provider": "deepseek",
    "family": "deepseek-r1",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 64000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00055,
    "costPer1kOutput": 0.00219,
    "qualityScore": 90,
    "speedScore": 72,
    "release": "stable",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Reasoning model. Override costs in models.registry for exact estimates."
  },
  "deepseek/deepseek-reasoner": {
    "provider": "deepseek",
    "family": "deepseek-reasoner",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 64000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 86,
    "speedScore": 70,
    "release": "stable",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Reasoning model. Override costs in models.registry for exact estimates."
  },
  "deepseek/deepseek-v3": {
    "provider": "deepseek",
    "family": "deepseek-v3",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 64000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00014000000000000001,
    "costPer1kOutput": 0.00028000000000000003,
    "qualityScore": 88,
    "speedScore": 86,
    "release": "stable",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing and limits vary by DeepSeek account; override costs in models.registry for exact estimates."
  },
  "gemini-1.5-flash": {
    "provider": "google",
    "family": "gemini-1.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.000075,
    "costPer1kOutput": 0.0003,
    "costPer1kCachedInput": 0.00001875,
    "qualityScore": 72,
    "speedScore": 90,
    "release": "2024",
    "knowledgeCutoff": "2024",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-1.5-pro": {
    "provider": "google",
    "family": "gemini-1.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 2000000,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.005,
    "costPer1kCachedInput": 0.0003125,
    "qualityScore": 80,
    "speedScore": 70,
    "release": "2024",
    "knowledgeCutoff": "2024",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-2.0-flash": {
    "provider": "google",
    "family": "gemini-2.0",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 78,
    "speedScore": 94,
    "release": "2025-02",
    "knowledgeCutoff": "2024-08",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-2.5-flash": {
    "provider": "google",
    "family": "gemini-2.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0025,
    "costPer1kCachedInput": 0.000075,
    "qualityScore": 86,
    "speedScore": 94,
    "release": "2025",
    "knowledgeCutoff": "2025-01",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-2.5-flash-lite": {
    "provider": "google",
    "family": "gemini-2.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 76,
    "speedScore": 98,
    "release": "2025",
    "knowledgeCutoff": "2025-01",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-2.5-flash-lite-preview-09-2025": {
    "provider": "google",
    "family": "gemini-2.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 76,
    "speedScore": 98,
    "release": "2025-09",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-2.5-pro": {
    "provider": "google",
    "family": "gemini-2.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0003125,
    "qualityScore": 92,
    "speedScore": 76,
    "release": "2025-06",
    "knowledgeCutoff": "2025-01",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3-flash-preview": {
    "provider": "google",
    "family": "gemini-3",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0005,
    "costPer1kOutput": 0.003,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 90,
    "speedScore": 94,
    "release": "2025-12",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3-pro-image-preview": {
    "provider": "google",
    "family": "gemini-3-image",
    "modalities": [
      "text",
      "vision",
      "image"
    ],
    "streaming": true,
    "toolCalling": false,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 65536,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 88,
    "speedScore": 70,
    "release": "2025-11",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3-pro-preview": {
    "provider": "google",
    "family": "gemini-3",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 96,
    "speedScore": 76,
    "release": "2025-11",
    "knowledgeCutoff": "2025-01",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Deprecated and shut down by Google on 2026-03-09; migrate to gemini-3.1-pro-preview."
  },
  "gemini-3.1-flash-lite-preview": {
    "provider": "google",
    "family": "gemini-3.1",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 86,
    "speedScore": 98,
    "release": "2026",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.1-pro-preview": {
    "provider": "google",
    "family": "gemini-3.1",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 97,
    "speedScore": 76,
    "release": "2026-02",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.1-pro-preview-customtools": {
    "provider": "google",
    "family": "gemini-3.1",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 97,
    "speedScore": 74,
    "release": "2026-02",
    "knowledgeCutoff": "2025-01",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.5-flash": {
    "provider": "google",
    "family": "gemini-3.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 90,
    "speedScore": 96,
    "release": "2026",
    "knowledgeCutoff": "2025-10",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.5-pro": {
    "provider": "google",
    "family": "gemini-3.5",
    "modalities": [
      "text",
      "vision",
      "audio",
      "video",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 2000000,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.005,
    "costPer1kCachedInput": 0.0003125,
    "qualityScore": 98,
    "speedScore": 76,
    "release": "2026",
    "knowledgeCutoff": "2025-10",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gpt-4.1": {
    "provider": "openai",
    "family": "gpt-4.1",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.008,
    "qualityScore": 88,
    "speedScore": 80,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4.1-mini": {
    "provider": "openai",
    "family": "gpt-4.1",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0004,
    "costPer1kOutput": 0.0016,
    "qualityScore": 82,
    "speedScore": 94,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4.1-nano": {
    "provider": "openai",
    "family": "gpt-4.1",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "qualityScore": 74,
    "speedScore": 98,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4.5-preview": {
    "provider": "openai",
    "family": "gpt-4.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.075,
    "costPer1kOutput": 0.15,
    "qualityScore": 92,
    "speedScore": 78,
    "release": "2025",
    "status": "preview",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4o": {
    "provider": "openai",
    "family": "gpt-4o",
    "modalities": [
      "text",
      "vision",
      "audio"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.0025,
    "costPer1kOutput": 0.01,
    "qualityScore": 84,
    "speedScore": 84,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses",
      "realtime"
    ]
  },
  "gpt-4o-mini": {
    "provider": "openai",
    "family": "gpt-4o",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.0006,
    "qualityScore": 76,
    "speedScore": 96,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5": {
    "provider": "openai",
    "family": "gpt-5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 92,
    "speedScore": 80,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5-chat-latest": {
    "provider": "openai",
    "family": "gpt-5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 90,
    "speedScore": 82,
    "release": "latest",
    "knowledgeCutoff": "2024-09-30",
    "status": "latest",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5-codex": {
    "provider": "openai",
    "family": "codex",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 93,
    "speedScore": 78,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5-mini": {
    "provider": "openai",
    "family": "gpt-5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00025,
    "costPer1kOutput": 0.002,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 88,
    "speedScore": 94,
    "release": "2025",
    "knowledgeCutoff": "2024-05-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5-nano": {
    "provider": "openai",
    "family": "gpt-5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00005,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000005000000000000001,
    "qualityScore": 78,
    "speedScore": 99,
    "release": "2025",
    "knowledgeCutoff": "2024-05-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.1": {
    "provider": "openai",
    "family": "gpt-5.1",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 94,
    "speedScore": 82,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.2": {
    "provider": "openai",
    "family": "gpt-5.2",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00175,
    "costPer1kOutput": 0.014,
    "costPer1kCachedInput": 0.00017500000000000003,
    "qualityScore": 96,
    "speedScore": 82,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.2-codex": {
    "provider": "openai",
    "family": "codex",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00175,
    "costPer1kOutput": 0.014,
    "costPer1kCachedInput": 0.00017500000000000003,
    "qualityScore": 96,
    "speedScore": 78,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.2-pro": {
    "provider": "openai",
    "family": "gpt-5.2",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.03,
    "costPer1kOutput": 0.18,
    "costPer1kCachedInput": 0.003,
    "qualityScore": 98,
    "speedScore": 55,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.4": {
    "provider": "openai",
    "family": "gpt-5.4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0025,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00025,
    "qualityScore": 97,
    "speedScore": 85,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.4-mini": {
    "provider": "openai",
    "family": "gpt-5.4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00075,
    "costPer1kOutput": 0.0045,
    "costPer1kCachedInput": 0.00007500000000000001,
    "qualityScore": 92,
    "speedScore": 94,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.4-nano": {
    "provider": "openai",
    "family": "gpt-5.4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0002,
    "costPer1kOutput": 0.00125,
    "costPer1kCachedInput": 0.000020000000000000005,
    "qualityScore": 84,
    "speedScore": 98,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.4-pro": {
    "provider": "openai",
    "family": "gpt-5.4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.03,
    "costPer1kOutput": 0.18,
    "costPer1kCachedInput": 0.003,
    "qualityScore": 99,
    "speedScore": 55,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.5": {
    "provider": "openai",
    "family": "gpt-5.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.03,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 99,
    "speedScore": 82,
    "release": "2026",
    "knowledgeCutoff": "2025-12-01",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.5-pro": {
    "provider": "openai",
    "family": "gpt-5.5",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.03,
    "costPer1kOutput": 0.18,
    "costPer1kCachedInput": 0.003,
    "qualityScore": 100,
    "speedScore": 55,
    "release": "2026",
    "knowledgeCutoff": "2025-12-01",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.6-luna": {
    "provider": "openai",
    "family": "gpt-5.6",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.001,
    "costPer1kOutput": 0.006,
    "costPer1kCachedInput": 0.0001,
    "qualityScore": 94,
    "speedScore": 96,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "OpenAI GPT-5.6 model optimized for cost-sensitive, high-volume workloads."
  },
  "gpt-5.6-sol": {
    "provider": "openai",
    "family": "gpt-5.6",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.03,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 100,
    "speedScore": 78,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "OpenAI flagship model for complex reasoning and coding."
  },
  "gpt-5.6-terra": {
    "provider": "openai",
    "family": "gpt-5.6",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0025,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00025,
    "qualityScore": 98,
    "speedScore": 86,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "OpenAI GPT-5.6 model balanced for intelligence and cost."
  },
  "gpt-oss-120b": {
    "provider": "openai",
    "family": "gpt-oss",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "maxContextTokens": 131000,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 78,
    "speedScore": 70,
    "release": "2025",
    "status": "stable",
    "endpoints": []
  },
  "gpt-oss-20b": {
    "provider": "openai",
    "family": "gpt-oss",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "maxContextTokens": 131000,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 68,
    "speedScore": 88,
    "release": "2025",
    "status": "stable",
    "endpoints": []
  },
  "groq/groq/compound": {
    "provider": "groq",
    "family": "compound",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 82,
    "speedScore": 94,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Groq Compound is a hosted agentic system with built-in tools; pricing is not token-metered in the model table."
  },
  "groq/groq/compound-mini": {
    "provider": "groq",
    "family": "compound",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 76,
    "speedScore": 96,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Groq Compound Mini is a hosted agentic system with built-in tools; pricing is not token-metered in the model table."
  },
  "groq/llama-3.1-8b-instant": {
    "provider": "groq",
    "family": "llama-3.1",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 131072,
    "costPer1kInput": 0.00005,
    "costPer1kOutput": 0.00008,
    "qualityScore": 68,
    "speedScore": 98,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/llama-3.3-70b-versatile": {
    "provider": "groq",
    "family": "llama-3.3",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0005899999999999999,
    "costPer1kOutput": 0.00079,
    "qualityScore": 80,
    "speedScore": 92,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/meta-llama/llama-4-scout-17b-16e-instruct": {
    "provider": "groq",
    "family": "llama-4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00011,
    "costPer1kOutput": 0.00034,
    "qualityScore": 78,
    "speedScore": 97,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/meta-llama/llama-prompt-guard-2-22m": {
    "provider": "groq",
    "family": "prompt-guard",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 512,
    "maxOutputTokens": 512,
    "costPer1kInput": 0.000029999999999999997,
    "costPer1kOutput": 0.000029999999999999997,
    "qualityScore": 55,
    "speedScore": 100,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/meta-llama/llama-prompt-guard-2-86m": {
    "provider": "groq",
    "family": "prompt-guard",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 512,
    "maxOutputTokens": 512,
    "costPer1kInput": 0.00004,
    "costPer1kOutput": 0.00004,
    "qualityScore": 58,
    "speedScore": 100,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/openai/gpt-oss-120b": {
    "provider": "groq",
    "family": "gpt-oss",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.0006,
    "qualityScore": 86,
    "speedScore": 96,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/openai/gpt-oss-20b": {
    "provider": "groq",
    "family": "gpt-oss",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.000075,
    "costPer1kOutput": 0.0003,
    "qualityScore": 78,
    "speedScore": 100,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/openai/gpt-oss-safeguard-20b": {
    "provider": "groq",
    "family": "safety",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.000075,
    "costPer1kOutput": 0.0003,
    "qualityScore": 70,
    "speedScore": 100,
    "release": "2025",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/qwen/qwen3-32b": {
    "provider": "groq",
    "family": "qwen3",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 40960,
    "costPer1kInput": 0.00029,
    "costPer1kOutput": 0.0005899999999999999,
    "qualityScore": 76,
    "speedScore": 90,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "llamacpp/local-model": {
    "provider": "llamacpp",
    "family": "local",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 8192,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 65,
    "speedScore": 75,
    "release": "local",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Placeholder for llama.cpp OpenAI-compatible server. Use an explicit llamacpp/<loaded-model> name for direct routing."
  },
  "lmstudio/local-model": {
    "provider": "lmstudio",
    "family": "local",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 8192,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 65,
    "speedScore": 75,
    "release": "local",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Placeholder for LM Studio. Use an explicit lmstudio/<loaded-model> name for direct routing."
  },
  "mistral/codestral-2508": {
    "provider": "mistral",
    "family": "codestral",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0009,
    "qualityScore": 84,
    "speedScore": 86,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Code model. Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/devstral-2512": {
    "provider": "mistral",
    "family": "devstral-2",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0004,
    "costPer1kOutput": 0.002,
    "qualityScore": 86,
    "speedScore": 84,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Code-agent model."
  },
  "mistral/magistral-medium-2509": {
    "provider": "mistral",
    "family": "magistral-medium-1.2",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.005,
    "qualityScore": 88,
    "speedScore": 70,
    "release": "2025-09",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Reasoning model. Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/ministral-3b": {
    "provider": "mistral",
    "family": "ministral-3b",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00004,
    "costPer1kOutput": 0.00004,
    "qualityScore": 75,
    "speedScore": 96,
    "release": "2024-10",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/ministral-8b": {
    "provider": "mistral",
    "family": "ministral-8b",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0001,
    "qualityScore": 80,
    "speedScore": 94,
    "release": "2024-10",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/mistral-large-2512": {
    "provider": "mistral",
    "family": "mistral-large-3",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.006,
    "qualityScore": 88,
    "speedScore": 76,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/mistral-medium-3-5": {
    "provider": "mistral",
    "family": "mistral-medium-3.5",
    "modalities": [
      "text",
      "vision",
      "pdf"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0015,
    "costPer1kOutput": 0.0075,
    "qualityScore": 90,
    "speedScore": 78,
    "release": "2026-04",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/mistral-moderation-2603": {
    "provider": "mistral",
    "family": "moderation",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 70,
    "speedScore": 92,
    "release": "2026-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Moderation model, not intended for normal chat completions."
  },
  "mistral/mistral-small-2603": {
    "provider": "mistral",
    "family": "mistral-small-4",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0002,
    "costPer1kOutput": 0.0006,
    "qualityScore": 82,
    "speedScore": 92,
    "release": "2026-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/pixtral-12b": {
    "provider": "mistral",
    "family": "pixtral-12b",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.00015,
    "qualityScore": 82,
    "speedScore": 92,
    "release": "2024-09",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "mistral/pixtral-large-2411": {
    "provider": "mistral",
    "family": "pixtral-large-2411",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.006,
    "qualityScore": 88,
    "speedScore": 76,
    "release": "2024-11",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Pricing varies by deployment; override costs in models.registry if needed."
  },
  "o1": {
    "provider": "openai",
    "family": "o-series",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.015,
    "costPer1kOutput": 0.06,
    "qualityScore": 88,
    "speedScore": 60,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o1-mini": {
    "provider": "openai",
    "family": "o-series",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 128000,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.012,
    "qualityScore": 82,
    "speedScore": 80,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o3": {
    "provider": "openai",
    "family": "o-series",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.008,
    "qualityScore": 90,
    "speedScore": 66,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o3-mini": {
    "provider": "openai",
    "family": "o-series",
    "modalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.0011,
    "costPer1kOutput": 0.0044,
    "qualityScore": 84,
    "speedScore": 82,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o4-mini": {
    "provider": "openai",
    "family": "o-series",
    "modalities": [
      "text",
      "vision"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.0011,
    "costPer1kOutput": 0.0044,
    "qualityScore": 86,
    "speedScore": 88,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  }
};

export const GENERATED_MODEL_ALIASES: Record<string, string> = {
  "anthropic/balanced": "claude-sonnet-5-0",
  "anthropic/best": "claude-opus-4-8",
  "anthropic/fast": "claude-haiku-5-0",
  "claude-3-5-haiku-latest": "claude-3-5-haiku-20241022",
  "claude-3-5-sonnet-latest": "claude-3-5-sonnet-20241022",
  "claude-3-7-sonnet-latest": "claude-3-7-sonnet-20250219",
  "claude-fable-5": "claude-fable-5-0",
  "claude-fable-5.0": "claude-fable-5-0",
  "claude-haiku-3.5": "claude-3-5-haiku-20241022",
  "claude-haiku-4-5": "claude-haiku-4-5-20251001",
  "claude-haiku-4-5-latest": "claude-haiku-4-5-20251001",
  "claude-haiku-4.5": "claude-haiku-4-5-20251001",
  "claude-opus-4": "claude-opus-4-20250514",
  "claude-opus-4-0": "claude-opus-4-20250514",
  "claude-opus-4-1": "claude-opus-4-1-20250805",
  "claude-opus-4-5": "claude-opus-4-5-20251101",
  "claude-opus-4-5-latest": "claude-opus-4-5-20251101",
  "claude-opus-4-6-latest": "claude-opus-4-6",
  "claude-opus-4-7-latest": "claude-opus-4-7",
  "claude-opus-4.1": "claude-opus-4-1-20250805",
  "claude-opus-4.5": "claude-opus-4-5-20251101",
  "claude-opus-4.6": "claude-opus-4-6",
  "claude-opus-4.7": "claude-opus-4-7",
  "claude-opus-4.8": "claude-opus-4-8",
  "claude-sonnet-3.5": "claude-3-5-sonnet-20241022",
  "claude-sonnet-3.7": "claude-3-7-sonnet-20250219",
  "claude-sonnet-4": "claude-sonnet-4-20250514",
  "claude-sonnet-4-0": "claude-sonnet-4-20250514",
  "claude-sonnet-4-6-latest": "claude-sonnet-4-6",
  "claude-sonnet-4.6": "claude-sonnet-4-6",
  "cohere/best": "cohere/command-a-03-2025",
  "cohere/fast": "cohere/command-r7b-12-2024",
  "cohere/reasoning": "cohere/command-a-reasoning-08-2025",
  "cohere/vision": "cohere/command-a-vision-07-2025",
  "deepseek/balanced": "deepseek/deepseek-chat",
  "deepseek/best": "deepseek/deepseek-reasoner",
  "deepseek/fast": "deepseek/deepseek-chat",
  "gemini-flash-latest": "gemini-3-flash-preview",
  "gemini-flash-lite-latest": "gemini-3.1-flash-lite-preview",
  "gemini-pro-latest": "gemini-3.1-pro-preview",
  "google/balanced": "gemini-3.5-pro",
  "google/best": "gemini-3.5-pro",
  "google/cheap": "gemini-3.5-flash",
  "google/fast": "gemini-3.5-flash",
  "gpt-5.6": "gpt-5.6-sol",
  "groq/best": "groq/openai/gpt-oss-120b",
  "groq/cheap": "groq/llama-3.1-8b-instant",
  "groq/compound": "groq/groq/compound",
  "groq/fast": "groq/openai/gpt-oss-20b",
  "mistral/balanced": "mistral/ministral-8b",
  "mistral/best": "mistral/pixtral-large-2411",
  "mistral/coding": "mistral/pixtral-12b",
  "mistral/devstral-2": "mistral/devstral-2512",
  "mistral/fast": "mistral/ministral-3b",
  "mistral/mistral-large-3": "mistral/mistral-large-2512",
  "mistral/mistral-small-4": "mistral/mistral-small-2603",
  "openai/balanced": "gpt-5.6-terra",
  "openai/best": "gpt-5.6-sol",
  "openai/cheap": "gpt-5.6-luna",
  "openai/codex": "gpt-5-codex",
  "openai/coding": "gpt-5.6-sol",
  "openai/fast": "gpt-5.6-luna",
  "openai/pro": "gpt-5.5-pro"
};

export const GENERATED_ALIAS_METADATA: Record<string, AliasMetadata> = {
  "anthropic/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "anthropic/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "anthropic/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-3-5-haiku-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-3-5-sonnet-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-3-7-sonnet-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-fable-5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-fable-5.0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-haiku-3.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-haiku-4-5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-haiku-4-5-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-haiku-4.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-1": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-5-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-6-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4-7-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4.1": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4.7": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-opus-4.8": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-3.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-3.7": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-4": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-4-0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-4-6-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "claude-sonnet-4.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "cohere/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "cohere/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "cohere/reasoning": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "cohere/vision": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "deepseek/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "deepseek/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "deepseek/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "gemini-flash-latest": {
    "stage": "preview",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "gemini-flash-lite-latest": {
    "stage": "preview",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "gemini-pro-latest": {
    "stage": "preview",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "google/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "google/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "google/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "google/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "gpt-5.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "groq/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "groq/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "groq/compound": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "groq/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "mistral/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "mistral/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "mistral/coding": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "mistral/devstral-2": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "mistral/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "mistral/mistral-large-3": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "mistral/mistral-small-4": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-08-25"
  },
  "openai/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/codex": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/coding": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  },
  "openai/pro": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-08-25"
  }
};

/** Count of generated entries, so a drift check can report a difference without a deep compare. */
export const GENERATED_MODEL_COUNT = 101;
