// Generated by scripts/generate-model-registry.mjs from data/models/. Do not edit by hand.
// Sources: aliases.json, anthropic.json, cohere.json, deepseek.json, google.json, groq.json, llamacpp.json, lmstudio.json, mistral.json, openai.json, provenance.json
// Run `npm run registry:generate` after changing the data, and `npm run registry:check` to verify.

import type { AliasMetadata, ModelCapabilities } from '../types/providers.js';

/** Provenance of the generated data, mirroring data/models/provenance.json. */
export const GENERATED_REGISTRY_PROVENANCE = {
  "verifiedAt": "2026-10-02",
  "source": "provider documentation"
} as const;

/** Every model defined in the versioned provider data, sorted by name. */
export const GENERATED_MODELS: Record<string, ModelCapabilities> = {
  "claude-fable-5": {
    "provider": "anthropic",
    "family": "claude-fable-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.01,
    "costPer1kOutput": 0.05,
    "costPer1kCachedInput": 0.001,
    "costPer1kCacheWrite": 0.0125,
    "qualityScore": 98,
    "speedScore": 62,
    "release": "2026-06-09",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false,
    "notes": "Thinking is always on."
  },
  "claude-fable-5-1": {
    "provider": "anthropic",
    "family": "claude-fable-5.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": false,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.01,
    "costPer1kOutput": 0.05,
    "costPer1kCachedInput": 0.00025,
    "costPer1kCacheWrite": 0.0125,
    "qualityScore": 100,
    "speedScore": 62,
    "release": "2026-09-01",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false,
    "notes": "Thinking is always on. Rejects forced tool choice."
  },
  "claude-haiku-4-5-20251001": {
    "provider": "anthropic",
    "family": "claude-haiku-4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.001,
    "costPer1kOutput": 0.005,
    "costPer1kCachedInput": 0.0001,
    "costPer1kCacheWrite": 0.00125,
    "qualityScore": 86,
    "speedScore": 98,
    "release": "2025-10-01",
    "knowledgeCutoff": "2025-02",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-5-20251101": {
    "provider": "anthropic",
    "family": "claude-opus-4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 92,
    "speedScore": 72,
    "release": "2025-11-24",
    "knowledgeCutoff": "2025-05",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-6": {
    "provider": "anthropic",
    "family": "claude-opus-4.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 94,
    "speedScore": 72,
    "release": "2026",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-opus-4-7": {
    "provider": "anthropic",
    "family": "claude-opus-4.7",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 95,
    "speedScore": 72,
    "release": "2026",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false
  },
  "claude-opus-4-8": {
    "provider": "anthropic",
    "family": "claude-opus-4.8",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 96,
    "speedScore": 74,
    "release": "2026",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false
  },
  "claude-opus-5": {
    "provider": "anthropic",
    "family": "claude-opus-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.025,
    "costPer1kCachedInput": 0.0005,
    "costPer1kCacheWrite": 0.00625,
    "qualityScore": 98,
    "speedScore": 74,
    "release": "2026-07-24",
    "knowledgeCutoff": "2026-05",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false,
    "notes": "Thinking turns off only at effort high or below."
  },
  "claude-opus-5-5": {
    "provider": "anthropic",
    "family": "claude-opus-5.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": false,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.004,
    "costPer1kOutput": 0.02,
    "costPer1kCachedInput": 0.0002,
    "costPer1kCacheWrite": 0.005,
    "qualityScore": 99,
    "speedScore": 76,
    "release": "2026-09-22",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false,
    "notes": "Thinking is always on, at effort medium by default. Rejects forced tool choice."
  },
  "claude-sonnet-4-5-20250929": {
    "provider": "anthropic",
    "family": "claude-sonnet-4.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ],
      "maxTokens": 48000
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 200000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 90,
    "speedScore": 86,
    "release": "2025-09-29",
    "knowledgeCutoff": "2025-01",
    "status": "deprecated",
    "endpoints": [
      "messages"
    ],
    "notes": "Anthropic retires it on 2026-11-30; migrate to claude-sonnet-5-5."
  },
  "claude-sonnet-4-6": {
    "provider": "anthropic",
    "family": "claude-sonnet-4.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": true,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0.003,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00030000000000000003,
    "costPer1kCacheWrite": 0.00375,
    "qualityScore": 92,
    "speedScore": 88,
    "release": "2026",
    "knowledgeCutoff": "2025-08",
    "status": "stable",
    "endpoints": [
      "messages"
    ]
  },
  "claude-sonnet-5": {
    "provider": "anthropic",
    "family": "claude-sonnet-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0002,
    "costPer1kCacheWrite": 0.0025,
    "qualityScore": 95,
    "speedScore": 88,
    "release": "2026-06-30",
    "knowledgeCutoff": "2026-01",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false
  },
  "claude-sonnet-5-5": {
    "provider": "anthropic",
    "family": "claude-sonnet-5.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": true,
      "ttls": [
        "5m",
        "1h"
      ],
      "minTokens": 1024,
      "maxBreakpoints": 4
    },
    "toolChoice": false,
    "parallelToolCalls": true,
    "topK": false,
    "penalties": false,
    "seed": false,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0002,
    "costPer1kCacheWrite": 0.0025,
    "qualityScore": 97,
    "speedScore": 88,
    "release": "2026-09-28",
    "knowledgeCutoff": "2026-06",
    "status": "stable",
    "endpoints": [
      "messages"
    ],
    "sampling": false,
    "notes": "Effort none turns off up-front thinking only, at effort high or below. Rejects forced tool choice."
  },
  "cohere/c4ai-aya-expanse-32b": {
    "provider": "cohere",
    "family": "aya-expanse",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 76,
    "speedScore": 84,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/c4ai-aya-vision-32b": {
    "provider": "cohere",
    "family": "aya-vision",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 16000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 78,
    "speedScore": 78,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-03-2025": {
    "provider": "cohere",
    "family": "command-a",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 256000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 86,
    "speedScore": 80,
    "release": "2025-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-plus-05-2026": {
    "provider": "cohere",
    "family": "command-a-plus",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 90,
    "speedScore": 74,
    "release": "2026-05",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-reasoning-08-2025": {
    "provider": "cohere",
    "family": "command-a-reasoning",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": true,
    "maxContextTokens": 256000,
    "maxOutputTokens": 32000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 88,
    "speedScore": 68,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-translate-08-2025": {
    "provider": "cohere",
    "family": "command-a-translate",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 82,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-a-vision-07-2025": {
    "provider": "cohere",
    "family": "command-a-vision",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 78,
    "release": "2025-07",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r-08-2024": {
    "provider": "cohere",
    "family": "command-r",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 76,
    "speedScore": 92,
    "release": "2024-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r-plus-08-2024": {
    "provider": "cohere",
    "family": "command-r-plus",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 80,
    "speedScore": 82,
    "release": "2024-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/command-r7b-12-2024": {
    "provider": "cohere",
    "family": "command-r7b",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 74,
    "speedScore": 94,
    "release": "2024-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/north-mini-code-1-0": {
    "provider": "cohere",
    "family": "north-mini-code",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 256000,
    "maxOutputTokens": 64000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 84,
    "speedScore": 86,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/north-small-translate-1-0": {
    "provider": "cohere",
    "family": "north-small-translate",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 16000,
    "maxOutputTokens": 16000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 80,
    "speedScore": 92,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/tiny-aya-earth": {
    "provider": "cohere",
    "family": "tiny-aya",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 62,
    "speedScore": 98,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/tiny-aya-fire": {
    "provider": "cohere",
    "family": "tiny-aya",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 62,
    "speedScore": 98,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/tiny-aya-global": {
    "provider": "cohere",
    "family": "tiny-aya",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 62,
    "speedScore": 98,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "cohere/tiny-aya-water": {
    "provider": "cohere",
    "family": "tiny-aya",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": false,
    "reasoning": false,
    "maxContextTokens": 8000,
    "maxOutputTokens": 8000,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 62,
    "speedScore": 98,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Cohere pricing is deployment/plan dependent; override costs in models.registry for exact estimates."
  },
  "deepseek/deepseek-flash": {
    "provider": "deepseek",
    "family": "deepseek-v4.1-flash",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 384000,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0012,
    "qualityScore": 88,
    "speedScore": 90,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Thinks by default. Peak price; off-peak hours (outside 01:00-04:00 and 06:00-10:00 UTC on weekdays) cost half.",
    "costPer1kCachedInput": 0.000006
  },
  "deepseek/deepseek-v4-pro": {
    "provider": "deepseek",
    "family": "deepseek-v4-pro",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 384000,
    "costPer1kInput": 0.00132,
    "costPer1kOutput": 0.00396,
    "qualityScore": 93,
    "speedScore": 74,
    "release": "2026-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Thinks by default. Peak price; off-peak hours (outside 01:00-04:00 and 06:00-10:00 UTC on weekdays) cost half.",
    "costPer1kCachedInput": 0.000044
  },
  "gemini-2.5-flash": {
    "provider": "google",
    "family": "gemini-2.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0025,
    "costPer1kCachedInput": 0.000075,
    "qualityScore": 80,
    "speedScore": 94,
    "release": "2025",
    "knowledgeCutoff": "2025-01",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Google limits it to existing users and recommends Gemini 3 for new work."
  },
  "gemini-2.5-flash-lite": {
    "provider": "google",
    "family": "gemini-2.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 72,
    "speedScore": 98,
    "release": "2025",
    "knowledgeCutoff": "2025-01",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Google limits it to existing users and recommends Gemini 3 for new work."
  },
  "gemini-2.5-pro": {
    "provider": "google",
    "family": "gemini-2.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0003125,
    "qualityScore": 86,
    "speedScore": 76,
    "release": "2025-06",
    "knowledgeCutoff": "2025-01",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Google limits it to existing users and recommends Gemini 3 for new work."
  },
  "gemini-3-flash-preview": {
    "provider": "google",
    "family": "gemini-3",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0005,
    "costPer1kOutput": 0.003,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 88,
    "speedScore": 94,
    "release": "2025-12",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Google names gemini-3.6-flash as its replacement."
  },
  "gemini-3-pro-image": {
    "provider": "google",
    "family": "gemini-3-image",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text",
      "image"
    ],
    "streaming": true,
    "toolCalling": false,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 65536,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.12,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 88,
    "speedScore": 70,
    "release": "2025-11",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ],
    "notes": "The output price is the image rate; text output costs less."
  },
  "gemini-3.1-flash-image": {
    "provider": "google",
    "family": "gemini-3.1-image",
    "inputModalities": [
      "text",
      "image",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text",
      "image"
    ],
    "streaming": true,
    "toolCalling": false,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0005,
    "costPer1kOutput": 0.06,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 84,
    "speedScore": 86,
    "release": "2026-02",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ],
    "notes": "The output price is the image rate; text output costs less."
  },
  "gemini-3.1-flash-lite": {
    "provider": "google",
    "family": "gemini-3.1",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00025,
    "costPer1kOutput": 0.0015,
    "costPer1kCachedInput": 0.0000625,
    "qualityScore": 82,
    "speedScore": 98,
    "release": "2026",
    "status": "deprecated",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Google shuts it down on 2027-05-07; migrate to gemini-3.5-flash-lite."
  },
  "gemini-3.1-pro-preview": {
    "provider": "google",
    "family": "gemini-3.1",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 97,
    "speedScore": 76,
    "release": "2026-02",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.1-pro-preview-customtools": {
    "provider": "google",
    "family": "gemini-3.1",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 97,
    "speedScore": 74,
    "release": "2026-02",
    "status": "preview",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.5-flash": {
    "provider": "google",
    "family": "gemini-3.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0015,
    "costPer1kOutput": 0.009,
    "costPer1kCachedInput": 0.000375,
    "qualityScore": 90,
    "speedScore": 94,
    "release": "2026-05",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.5-flash-lite": {
    "provider": "google",
    "family": "gemini-3.5",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0025,
    "costPer1kCachedInput": 0.000075,
    "qualityScore": 84,
    "speedScore": 97,
    "release": "2026-07",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ]
  },
  "gemini-3.6-flash": {
    "provider": "google",
    "family": "gemini-3.6",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00075,
    "costPer1kOutput": 0.00375,
    "costPer1kCachedInput": 0.0001875,
    "qualityScore": 91,
    "speedScore": 94,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Prices double on 2027-01-01, to $1.50 input and $7.50 output per million tokens."
  },
  "gemini-3.7-flash": {
    "provider": "google",
    "family": "gemini-3.7",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00075,
    "costPer1kOutput": 0.00375,
    "costPer1kCachedInput": 0.0001875,
    "qualityScore": 93,
    "speedScore": 94,
    "release": "2026",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Prices double on 2027-01-01, to $1.50 input and $7.50 output per million tokens."
  },
  "gemini-3.8-flash": {
    "provider": "google",
    "family": "gemini-3.8",
    "inputModalities": [
      "text",
      "image",
      "audio",
      "video",
      "pdf"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m",
        "1h"
      ]
    },
    "toolChoice": true,
    "topK": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1048576,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00075,
    "costPer1kOutput": 0.00375,
    "costPer1kCachedInput": 0.0001875,
    "qualityScore": 95,
    "speedScore": 94,
    "release": "2026-09",
    "status": "stable",
    "endpoints": [
      "generateContent"
    ],
    "notes": "Prices double on 2027-01-01, to $1.50 input and $7.50 output per million tokens."
  },
  "gpt-4.1": {
    "provider": "openai",
    "family": "gpt-4.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.008,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 82,
    "speedScore": 80,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4.1-mini": {
    "provider": "openai",
    "family": "gpt-4.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0004,
    "costPer1kOutput": 0.0016,
    "costPer1kCachedInput": 0.0001,
    "qualityScore": 78,
    "speedScore": 94,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4.1-nano": {
    "provider": "openai",
    "family": "gpt-4.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 1047576,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 70,
    "speedScore": 98,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-4o": {
    "provider": "openai",
    "family": "gpt-4o",
    "inputModalities": [
      "text",
      "image",
      "audio"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.0025,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.00125,
    "qualityScore": 78,
    "speedScore": 84,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses",
      "realtime"
    ]
  },
  "gpt-4o-mini": {
    "provider": "openai",
    "family": "gpt-4o",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.0006,
    "costPer1kCachedInput": 0.000075,
    "qualityScore": 72,
    "speedScore": 96,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5": {
    "provider": "openai",
    "family": "gpt-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 88,
    "speedScore": 80,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2026-12-11; migrate to gpt-5.6-sol."
  },
  "gpt-5-mini": {
    "provider": "openai",
    "family": "gpt-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00025,
    "costPer1kOutput": 0.002,
    "costPer1kCachedInput": 0.000025,
    "qualityScore": 84,
    "speedScore": 94,
    "release": "2025",
    "knowledgeCutoff": "2024-05-31",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2026-12-11; migrate to gpt-5.6-terra."
  },
  "gpt-5-nano": {
    "provider": "openai",
    "family": "gpt-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00005,
    "costPer1kOutput": 0.0004,
    "costPer1kCachedInput": 0.000005000000000000001,
    "qualityScore": 76,
    "speedScore": 99,
    "release": "2025",
    "knowledgeCutoff": "2024-05-31",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2026-12-11; migrate to gpt-5.6-luna."
  },
  "gpt-5-pro": {
    "provider": "openai",
    "family": "gpt-5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.015,
    "costPer1kOutput": 0.12,
    "costPer1kCachedInput": 0.0015,
    "qualityScore": 90,
    "speedScore": 50,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.1": {
    "provider": "openai",
    "family": "gpt-5.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00125,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.000125,
    "qualityScore": 90,
    "speedScore": 82,
    "release": "2025",
    "knowledgeCutoff": "2024-09-30",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2027-04-01; migrate to gpt-6-sol."
  },
  "gpt-5.2": {
    "provider": "openai",
    "family": "gpt-5.2",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00175,
    "costPer1kOutput": 0.014,
    "costPer1kCachedInput": 0.00017500000000000003,
    "qualityScore": 92,
    "speedScore": 82,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.2-codex": {
    "provider": "openai",
    "family": "codex",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00175,
    "costPer1kOutput": 0.014,
    "costPer1kCachedInput": 0.00017500000000000003,
    "qualityScore": 93,
    "speedScore": 78,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.2-pro": {
    "provider": "openai",
    "family": "gpt-5.2",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.021,
    "costPer1kOutput": 0.168,
    "costPer1kCachedInput": 0.0021000000000000003,
    "qualityScore": 94,
    "speedScore": 55,
    "release": "2025",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.3-codex": {
    "provider": "openai",
    "family": "codex",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00175,
    "costPer1kOutput": 0.014,
    "costPer1kCachedInput": 0.00017500000000000003,
    "qualityScore": 95,
    "speedScore": 78,
    "release": "2026",
    "knowledgeCutoff": "2025-08-31",
    "status": "deprecated",
    "endpoints": [
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2027-04-01; migrate to gpt-6-sol."
  },
  "gpt-5.4": {
    "provider": "openai",
    "family": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0025,
    "costPer1kOutput": 0.015,
    "costPer1kCachedInput": 0.00025,
    "qualityScore": 93,
    "speedScore": 85,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.4-mini": {
    "provider": "openai",
    "family": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.00075,
    "costPer1kOutput": 0.0045,
    "costPer1kCachedInput": 0.00007500000000000001,
    "qualityScore": 90,
    "speedScore": 94,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.4-nano": {
    "provider": "openai",
    "family": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 400000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0002,
    "costPer1kOutput": 0.00125,
    "costPer1kCachedInput": 0.000020000000000000005,
    "qualityScore": 82,
    "speedScore": 98,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2027-04-01; migrate to gpt-6-luna."
  },
  "gpt-5.4-pro": {
    "provider": "openai",
    "family": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.03,
    "costPer1kOutput": 0.18,
    "costPer1kCachedInput": 0.003,
    "qualityScore": 95,
    "speedScore": 55,
    "release": "2026-03",
    "knowledgeCutoff": "2025-08-31",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.5": {
    "provider": "openai",
    "family": "gpt-5.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1000000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.005,
    "costPer1kOutput": 0.03,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 96,
    "speedScore": 82,
    "release": "2026",
    "knowledgeCutoff": "2025-12-01",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "gpt-5.5-pro": {
    "provider": "openai",
    "family": "gpt-5.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": false,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.03,
    "costPer1kOutput": 0.18,
    "costPer1kCachedInput": 0.003,
    "qualityScore": 97,
    "speedScore": 55,
    "release": "2026",
    "knowledgeCutoff": "2025-12-01",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.6-luna": {
    "provider": "openai",
    "family": "gpt-5.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0002,
    "costPer1kOutput": 0.0012,
    "costPer1kCachedInput": 0.000020000000000000005,
    "qualityScore": 88,
    "speedScore": 96,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.6-sol": {
    "provider": "openai",
    "family": "gpt-5.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.004,
    "costPer1kOutput": 0.02,
    "costPer1kCachedInput": 0.0004,
    "qualityScore": 97,
    "speedScore": 78,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-5.6-terra": {
    "provider": "openai",
    "family": "gpt-5.6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.012,
    "costPer1kCachedInput": 0.0002,
    "qualityScore": 94,
    "speedScore": 86,
    "release": "2026-07",
    "knowledgeCutoff": "2026-02-16",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "gpt-6-astra": {
    "provider": "openai",
    "family": "gpt-6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.01,
    "costPer1kOutput": 0.05,
    "costPer1kCachedInput": 0.001,
    "qualityScore": 100,
    "speedScore": 70,
    "release": "2026",
    "knowledgeCutoff": "2026-04-30",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "costPer1kCacheWrite": 0.0125,
    "notes": "OpenAI flagship for the hardest reasoning and agentic work."
  },
  "gpt-6-luna": {
    "provider": "openai",
    "family": "gpt-6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0005,
    "costPer1kCachedInput": 0.000010000000000000003,
    "qualityScore": 90,
    "speedScore": 99,
    "release": "2026",
    "knowledgeCutoff": "2026-05-18",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "OpenAI model for high-volume, cost-sensitive work. Chat Completions calls tools only at reasoning effort none, so it is sent through Responses."
  },
  "gpt-6-sol": {
    "provider": "openai",
    "family": "gpt-6",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "none",
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0002,
    "qualityScore": 98,
    "speedScore": 84,
    "release": "2026",
    "knowledgeCutoff": "2026-04-20",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "Superseded by gpt-6.1-sol."
  },
  "gpt-6.1-sol": {
    "provider": "openai",
    "family": "gpt-6.1",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high",
        "xhigh",
        "max"
      ]
    },
    "promptCaching": {
      "explicit": false,
      "ttls": [
        "5m"
      ]
    },
    "toolChoice": true,
    "parallelToolCalls": true,
    "topK": false,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 1050000,
    "maxOutputTokens": 128000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.01,
    "costPer1kCachedInput": 0.0001,
    "qualityScore": 99,
    "speedScore": 84,
    "release": "2026",
    "knowledgeCutoff": "2026-04-30",
    "status": "stable",
    "endpoints": [
      "responses"
    ],
    "notes": "Near-Astra quality for coding, computer use, and professional work, at a lower price."
  },
  "gpt-oss-120b": {
    "provider": "openai",
    "family": "gpt-oss",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "maxContextTokens": 131000,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 78,
    "speedScore": 70,
    "release": "2025",
    "status": "stable",
    "endpoints": []
  },
  "gpt-oss-20b": {
    "provider": "openai",
    "family": "gpt-oss",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "maxContextTokens": 131000,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 68,
    "speedScore": 88,
    "release": "2025",
    "status": "stable",
    "endpoints": []
  },
  "groq/llama-3.1-8b-instant": {
    "provider": "groq",
    "family": "llama-3.1",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 131072,
    "costPer1kInput": 0.00005,
    "costPer1kOutput": 0.00008,
    "qualityScore": 64,
    "speedScore": 98,
    "release": "2024",
    "status": "deprecated",
    "endpoints": [
      "chat"
    ],
    "notes": "Groq ended on-demand access on 2026-08-16 and offers it through sales; migrate to groq/openai/gpt-oss-20b."
  },
  "groq/llama-3.3-70b-versatile": {
    "provider": "groq",
    "family": "llama-3.3",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 32768,
    "costPer1kInput": 0.0005899999999999999,
    "costPer1kOutput": 0.00079,
    "qualityScore": 76,
    "speedScore": 92,
    "release": "2024",
    "status": "deprecated",
    "endpoints": [
      "chat"
    ],
    "notes": "Groq ended on-demand access on 2026-08-16 and offers it through sales; migrate to groq/openai/gpt-oss-120b."
  },
  "groq/meta-llama/llama-prompt-guard-2-22m": {
    "provider": "groq",
    "family": "prompt-guard",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 512,
    "maxOutputTokens": 512,
    "costPer1kInput": 0.000029999999999999997,
    "costPer1kOutput": 0.000029999999999999997,
    "qualityScore": 55,
    "speedScore": 100,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/meta-llama/llama-prompt-guard-2-86m": {
    "provider": "groq",
    "family": "prompt-guard",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 512,
    "maxOutputTokens": 512,
    "costPer1kInput": 0.00004,
    "costPer1kOutput": 0.00004,
    "qualityScore": 58,
    "speedScore": 100,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/minimaxai/minimax-m2.7": {
    "provider": "groq",
    "family": "minimax-m2",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 196608,
    "maxOutputTokens": 131072,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 86,
    "speedScore": 88,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ],
    "notes": "Groq prices it through sales; override costs in models.registry."
  },
  "groq/openai/gpt-oss-120b": {
    "provider": "groq",
    "family": "gpt-oss",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.0006,
    "qualityScore": 86,
    "speedScore": 96,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/openai/gpt-oss-20b": {
    "provider": "groq",
    "family": "gpt-oss",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.000075,
    "costPer1kOutput": 0.0003,
    "qualityScore": 78,
    "speedScore": 100,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "groq/openai/gpt-oss-safeguard-20b": {
    "provider": "groq",
    "family": "safety",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 65536,
    "costPer1kInput": 0.000075,
    "costPer1kOutput": 0.0003,
    "qualityScore": 70,
    "speedScore": 100,
    "release": "2025",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "groq/qwen/qwen3.8-27b": {
    "provider": "groq",
    "family": "qwen3.8",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 131072,
    "maxOutputTokens": 16384,
    "costPer1kInput": 0.0008,
    "costPer1kOutput": 0.004,
    "qualityScore": 84,
    "speedScore": 90,
    "release": "2026",
    "status": "preview",
    "endpoints": [
      "chat"
    ]
  },
  "llamacpp/local-model": {
    "provider": "llamacpp",
    "family": "local",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 8192,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 65,
    "speedScore": 75,
    "release": "local",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Placeholder for llama.cpp OpenAI-compatible server. Use an explicit llamacpp/<loaded-model> name for direct routing."
  },
  "lmstudio/local-model": {
    "provider": "lmstudio",
    "family": "local",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 8192,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 65,
    "speedScore": 75,
    "release": "local",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Placeholder for LM Studio. Use an explicit lmstudio/<loaded-model> name for direct routing."
  },
  "mistral/codestral-2508": {
    "provider": "mistral",
    "family": "codestral",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0003,
    "costPer1kOutput": 0.0009,
    "qualityScore": 84,
    "speedScore": 86,
    "release": "2025-08",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Code model for fill-in-the-middle and code generation."
  },
  "mistral/ministral-14b-2512": {
    "provider": "mistral",
    "family": "ministral-3",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0002,
    "costPer1kOutput": 0.0002,
    "qualityScore": 80,
    "speedScore": 92,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/ministral-3b-2512": {
    "provider": "mistral",
    "family": "ministral-3",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0001,
    "costPer1kOutput": 0.0001,
    "qualityScore": 70,
    "speedScore": 97,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/ministral-8b-2512": {
    "provider": "mistral",
    "family": "ministral-3",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.00015,
    "qualityScore": 76,
    "speedScore": 95,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/mistral-large-2512": {
    "provider": "mistral",
    "family": "mistral-large-3",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0005,
    "costPer1kOutput": 0.0015,
    "qualityScore": 88,
    "speedScore": 80,
    "release": "2025-12",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/mistral-medium-2604": {
    "provider": "mistral",
    "family": "mistral-medium-3.5",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.0015,
    "costPer1kOutput": 0.0075,
    "qualityScore": 92,
    "speedScore": 78,
    "release": "2026-04",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "mistral/mistral-moderation-2603": {
    "provider": "mistral",
    "family": "moderation",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": false,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 128000,
    "maxOutputTokens": 4096,
    "costPer1kInput": 0,
    "costPer1kOutput": 0,
    "qualityScore": 70,
    "speedScore": 92,
    "release": "2026-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ],
    "notes": "Moderation model, not intended for normal chat completions."
  },
  "mistral/mistral-small-2603": {
    "provider": "mistral",
    "family": "mistral-small-4",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": true,
    "toolChoice": true,
    "parallelToolCalls": true,
    "seed": true,
    "penalties": true,
    "maxContextTokens": 262144,
    "maxOutputTokens": 8192,
    "costPer1kInput": 0.00015,
    "costPer1kOutput": 0.0006,
    "qualityScore": 84,
    "speedScore": 92,
    "release": "2026-03",
    "status": "stable",
    "endpoints": [
      "chat"
    ]
  },
  "o1": {
    "provider": "openai",
    "family": "o-series",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.015,
    "costPer1kOutput": 0.06,
    "qualityScore": 80,
    "speedScore": 60,
    "release": "2024",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o3": {
    "provider": "openai",
    "family": "o-series",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.002,
    "costPer1kOutput": 0.008,
    "costPer1kCachedInput": 0.0005,
    "qualityScore": 84,
    "speedScore": 66,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  },
  "o3-mini": {
    "provider": "openai",
    "family": "o-series",
    "inputModalities": [
      "text"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.0011,
    "costPer1kOutput": 0.0044,
    "costPer1kCachedInput": 0.00055,
    "qualityScore": 78,
    "speedScore": 82,
    "release": "2025",
    "status": "deprecated",
    "endpoints": [
      "chat",
      "responses"
    ],
    "notes": "OpenAI shuts it down on 2026-10-23; migrate to gpt-5.6-sol."
  },
  "o3-pro": {
    "provider": "openai",
    "family": "o-series",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": false,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.02,
    "costPer1kOutput": 0.08,
    "qualityScore": 86,
    "speedScore": 40,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "responses"
    ]
  },
  "o4-mini": {
    "provider": "openai",
    "family": "o-series",
    "inputModalities": [
      "text",
      "image"
    ],
    "outputModalities": [
      "text"
    ],
    "streaming": true,
    "toolCalling": true,
    "structuredOutputs": true,
    "jsonMode": true,
    "reasoning": {
      "efforts": [
        "low",
        "medium",
        "high"
      ]
    },
    "maxContextTokens": 200000,
    "maxOutputTokens": 100000,
    "costPer1kInput": 0.0011,
    "costPer1kOutput": 0.0044,
    "costPer1kCachedInput": 0.000275,
    "qualityScore": 80,
    "speedScore": 88,
    "release": "2025",
    "status": "stable",
    "endpoints": [
      "chat",
      "responses"
    ]
  }
};

export const GENERATED_MODEL_ALIASES: Record<string, string> = {
  "anthropic/balanced": "claude-sonnet-5-5",
  "anthropic/best": "claude-fable-5-1",
  "anthropic/fast": "claude-haiku-4-5-20251001",
  "claude-fable-5.0": "claude-fable-5",
  "claude-fable-5.1": "claude-fable-5-1",
  "claude-haiku-4-5": "claude-haiku-4-5-20251001",
  "claude-haiku-4-5-latest": "claude-haiku-4-5-20251001",
  "claude-haiku-4.5": "claude-haiku-4-5-20251001",
  "claude-opus-4-5": "claude-opus-4-5-20251101",
  "claude-opus-4-5-latest": "claude-opus-4-5-20251101",
  "claude-opus-4-6-latest": "claude-opus-4-6",
  "claude-opus-4-7-latest": "claude-opus-4-7",
  "claude-opus-4.5": "claude-opus-4-5-20251101",
  "claude-opus-4.6": "claude-opus-4-6",
  "claude-opus-4.7": "claude-opus-4-7",
  "claude-opus-4.8": "claude-opus-4-8",
  "claude-opus-5.0": "claude-opus-5",
  "claude-opus-5.5": "claude-opus-5-5",
  "claude-sonnet-4-5": "claude-sonnet-4-5-20250929",
  "claude-sonnet-4-6-latest": "claude-sonnet-4-6",
  "claude-sonnet-4.5": "claude-sonnet-4-5-20250929",
  "claude-sonnet-4.6": "claude-sonnet-4-6",
  "claude-sonnet-5.0": "claude-sonnet-5",
  "claude-sonnet-5.5": "claude-sonnet-5-5",
  "cohere/best": "cohere/command-a-plus-05-2026",
  "cohere/coding": "cohere/north-mini-code-1-0",
  "cohere/fast": "cohere/command-r7b-12-2024",
  "cohere/reasoning": "cohere/command-a-reasoning-08-2025",
  "cohere/vision": "cohere/command-a-vision-07-2025",
  "deepseek/balanced": "deepseek/deepseek-flash",
  "deepseek/best": "deepseek/deepseek-v4-pro",
  "deepseek/cheap": "deepseek/deepseek-flash",
  "deepseek/deepseek-v4-flash": "deepseek/deepseek-flash",
  "deepseek/fast": "deepseek/deepseek-flash",
  "gemini-flash-latest": "gemini-3.8-flash",
  "gemini-flash-lite-latest": "gemini-3.5-flash-lite",
  "gemini-pro-latest": "gemini-3.1-pro-preview",
  "google/balanced": "gemini-3.8-flash",
  "google/best": "gemini-3.1-pro-preview",
  "google/cheap": "gemini-3.5-flash-lite",
  "google/fast": "gemini-3.5-flash-lite",
  "gpt-5.6": "gpt-5.6-sol",
  "groq/best": "groq/openai/gpt-oss-120b",
  "groq/cheap": "groq/openai/gpt-oss-20b",
  "groq/fast": "groq/openai/gpt-oss-20b",
  "mistral/balanced": "mistral/mistral-small-2603",
  "mistral/best": "mistral/mistral-medium-2604",
  "mistral/cheap": "mistral/ministral-3b-2512",
  "mistral/coding": "mistral/codestral-2508",
  "mistral/fast": "mistral/ministral-8b-2512",
  "mistral/mistral-large-3": "mistral/mistral-large-2512",
  "mistral/mistral-medium-3.5": "mistral/mistral-medium-2604",
  "mistral/mistral-small-4": "mistral/mistral-small-2603",
  "openai/balanced": "gpt-6.1-sol",
  "openai/best": "gpt-6-astra",
  "openai/cheap": "gpt-6-luna",
  "openai/codex": "gpt-5.3-codex",
  "openai/coding": "gpt-6.1-sol",
  "openai/fast": "gpt-6-luna",
  "openai/pro": "gpt-5.5-pro"
};

export const GENERATED_ALIAS_METADATA: Record<string, AliasMetadata> = {
  "anthropic/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "anthropic/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "anthropic/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-fable-5.0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-fable-5.1": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-haiku-4-5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-haiku-4-5-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-haiku-4.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4-5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4-5-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4-6-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4-7-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4.7": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-4.8": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-5.0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-opus-5.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-4-5": {
    "stage": "deprecated",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-4-6-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-4.5": {
    "stage": "deprecated",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-4.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-5.0": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "claude-sonnet-5.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "cohere/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "cohere/coding": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "cohere/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "cohere/reasoning": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "cohere/vision": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "deepseek/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "deepseek/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "deepseek/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "deepseek/deepseek-v4-flash": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "deepseek/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "gemini-flash-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "gemini-flash-lite-latest": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "gemini-pro-latest": {
    "stage": "preview",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "google/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "google/best": {
    "stage": "preview",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "google/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "google/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "gpt-5.6": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "groq/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "groq/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "groq/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/coding": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "mistral/mistral-large-3": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "mistral/mistral-medium-3.5": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "mistral/mistral-small-4": {
    "stage": "stable",
    "floating": false,
    "verifiedAt": "2026-10-02"
  },
  "openai/balanced": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/best": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/cheap": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/codex": {
    "stage": "deprecated",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/coding": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/fast": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  },
  "openai/pro": {
    "stage": "stable",
    "floating": true,
    "verifiedAt": "2026-10-02"
  }
};

/** Count of generated entries, so a drift check can report a difference without a deep compare. */
export const GENERATED_MODEL_COUNT = 98;
